### ISSUE TITLE
iOS14 PHAuthorizationStatusLimited情况下ZLPhotoActionSheet展示的预览图片问题

### ISSUE THREAD

**Issue by feng-tianyou** [longitachi/ZLPhotoBrowser-objc#2]
在PHAuthorizationStatusLimited情况下ZLPhotoActionSheet展示的预览图片包含未选择图片的占位图，例如用户选择了6张图片可视，预览图显示8张，其中有两张属于多余的
<img width="308" alt="image" src="https://user-images.githubusercontent.com/14937470/96552131-f01a5380-12e5-11eb-977f-b1f07ffaeae7.png">
谢谢

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/issues/517#issuecomment-694129493

**Comment by feng-tianyou** [comment]
感谢作者

**Comment by longitachi** [comment]
建议迁移使用`Swift`版本，`oc`版本后面可能仅做必要适配，不在维护。
