### ISSUE TITLE
Frameworks/ZLPhotoBrowser_objc.framework/ZLPhotoBrowser.bundle

### ISSUE THREAD

**Issue by cuixiaocun** [longitachi/ZLPhotoBrowser-objc#3]
#define kZLPhotoBrowserFrameworkSrcName(file) [@"Frameworks/ZLPhotoBrowser_objc.framework/ZLPhotoBrowser.bundle" stringByAppendingPathComponent:file]

replace
#define kZLPhotoBrowserFrameworkSrcName(file) [@"Frameworks/ZLPhotoBrowser.framework/ZLPhotoBrowser.bundle" stringByAppendingPathComponent:file]

**Comment by longitachi** [comment]
有空了会修改下bundle获取方式，不再用这个宏定义了，就像swift版本中获取bundle一样

**Comment by xiaotaowuliang** [comment]
进入相册后点击图片显示大图，图片显示不出来怎么回事呢

**Comment by cuixiaocun** [comment]
> 进入相册后点击图片显示大图，图片显示不出来怎么回事呢
> ![image](https://user-images.githubusercontent.com/23495340/96975444-04ac5500-154d-11eb-9135-379d1d83eb85.png)

你是IOS14版本吧，你需要进设置设置一下吧

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/issues/523#issuecomment-699591817
