### ISSUE TITLE
ZLPhotoBrowser_objc

### ISSUE THREAD

**Issue by cuixiaocun** [longitachi/ZLPhotoBrowser-objc#4]
能把 ZLPhotoBrowser-objc  改为ZLPhotoBrowser_objc  导入到flutter作为插件出现问题ZLPhotoBrowser-objc not find

**Comment by longitachi** [comment]
建议使用[swift版本](https://github.com/longitachi/ZLPhotoBrowser)，swift版本功能更多更强大，这个oc版本后面可能除了必要的适配不在维护了
