### ISSUE TITLE
iOS 10.3 奔溃;

### ISSUE THREAD

**Issue by oneyian** [longitachi/ZLPhotoBrowser-objc#5]
原因：ZLDefine.h
代码242L，需要版本判断;

if (@available(iOS 13.0, *)) {
        return [UIImage imageNamed:name inBundle:NSBundle.zlPhotoBrowserBundle withConfiguration:nil];
    } else {
        return [UIImage imageNamed:name inBundle:NSBundle.zlPhotoBrowserBundle compatibleWithTraitCollection:nil];
    }

**Comment by longitachi** [comment]
这个接口是 iOS8.0，之后支持的，按理说不应该有这个问题。能帮试下 Swift 版本的 [ZLPhotoBrowser](https://github.com/longitachi/ZLPhotoBrowser) 在iOS10.3设备是否有崩溃问题吗？我这边没这个版本的设备，谢谢
```
@available(iOS 8.0, *)
public /*not inherited*/ init?(named name: String, in bundle: Bundle?, compatibleWith traitCollection: UITraitCollection?)
```

**Comment by oneyian** [comment]
![image](https://user-images.githubusercontent.com/19562817/99870249-b30aef00-2c0c-11eb-9a64-e65e495040df.png)
![image](https://user-images.githubusercontent.com/19562817/99869994-7ccc7000-2c0a-11eb-9eab-9d05d82aadfc.png)

**Comment by longitachi** [comment]
emmm，我看错方法了，swift版本用的是iOS8.0的，下次发版修改下。

**Comment by amiruljack** [comment]
i have this problem when using image_pickers 1.0.8+7 https://pub.dev/packages/image_pickers

**Comment by longitachi** [comment]
> i have this problem when using image_pickers 1.0.8+7 https://pub.dev/packages/image_pickers

I think this plugin should change the dependency on `ZLPhotoBrowser-objc`, and update to the latest version.

I recommend dependency on [ZLPhotoBrowser](https://github.com/longitachi/ZLPhotoBrowser) for this plugin, because this repo is no longer maintained.
