### ISSUE TITLE
iOS15导航栏适配

### ISSUE THREAD

**Issue by ipad4** [longitachi/ZLPhotoBrowser-objc#8]
iOS15导航栏需要适配

**Comment by longitachi** [comment]
oc版本的已经停止维护了，用[swift](https://github.com/longitachi/ZLPhotoBrowser)版本吧

**Comment by wscqs** [comment]
iOS15导航栏需要适配

**Comment by QiaoLansheng** [comment]
> oc版本的已经停止维护了，用[swift](https://github.com/longitachi/ZLPhotoBrowser)版本吧

这个是要桥接Swift版本过来用吗？

**Comment by wscqs** [comment]
来信已经收到。
